spring:
  liquibase:
    enabled: true
    default-schema: cookies
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1608
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
